version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '03:00'
    open-pull-requests-limit: 3
    reviewers:
      - FranciscoGileno
    ignore:
      - dependency-name: '@types/react'
        versions:
          - 17.0.1
          - 17.0.2
          - 17.0.3
      - dependency-name: husky
        versions:
          - 5.0.9
          - 5.1.0
          - 5.1.1
          - 5.1.3
          - 5.2.0
      - dependency-name: postcss-import
        versions:
          - 14.0.0
      - dependency-name: '@typescript-eslint/parser'
        versions:
          - 4.15.1
      - dependency-name: '@types/node'
        versions:
          - 14.14.25
          - 14.14.26
      - dependency-name: react-toastify
        versions:
          - 7.0.2
