version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:12.2.0-stretch
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules
      - run:
          name: Run Lint Checks
          command: yarn orion:lint --max-warnings=0 --format junit --output-file ../../reports/junit/eslint.xml
      - run:
          name: Run Tests
          command: yarn workspace @incognia/orion test --ci --maxWorkers=2 --reporters=default --reporters=jest-junit
      - store_test_results:
          path: ./reports

workflows:
  version: 2.1
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore: gh-pages
