version: 2

jobs:
  build:
    docker:
      - image: circleci/node:12.2.0-stretch
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules
      - run:
          name: Run Tests
          command: yarn workspace @inloco/orion test --ci --maxWorkers=2 --reporters=default --reporters=jest-junit
      - store_test_results:
          path: ./reports
    branches:
      ignore: gh-pages
